version: '3.7'
services:
  kafka-connect-service:
    build:
      context: ""
    container_name: kafka-service-connector
    command: python /app/main.py
    environment:
      KAFKA_SERVICE_INTERNAL_HOST: ${KAFKA_SERVICE_INTERNAL_HOST}
      KAFKA_SERVICE_INTERNAL_PORT: ${KAFKA_SERVICE_INTERNAL_PORT}
      KAFKA_SERVICE_INPUT_TOPIC: ${KAFKA_SERVICE_INPUT_TOPIC}
      KAFKA_SERVICE_OUTPUT_TOPIC: ${KAFKA_SERVICE_OUTPUT_TOPIC}
      KAFKA_SERVICE_GROUP_ID: ${KAFKA_SERVICE_GROUP_ID}
      KAFKA_SERVICE_PASSWORD: ${KAFKA_SERVICE_PASSWORD}
      KAFKA_SERVICE_USERNAME: ${KAFKA_SERVICE_USERNAME}
    networks:
      - kafka-streaming-app-network
    tty: true 
    stdin_open: true
networks:
  kafka-streaming-app-network:
    external: true